language: python
python:
  - "3.6"
install:
  - pip install --index-url https://test.pypi.org/simple/ -r requirements-test.txt --extra-index-url https://pypi.org/simple/ -r requirements.txt
script:
  - pytest
  - flake8 --ignore=F401 cloud_scanner_azure
before_deploy:
  # Generate Sphinx docs
  - make sphinx
  # Generate PIP package distros
  - pip install --upgrade setuptools wheel
  - python setup.py sdist bdist_wheel
deploy:
  # Deploy Sphinx docs to github pages
  - provider: pages
    skip_cleanup: true
    local-dir: docs/build/html
    github-token: ${GITHUB_TOKEN}
    keep-history: true
    on:
      tags: true
  # Deploy pypi package
  - provider: pypi
    skip_cleanup: true
    user:
      secure: "Rdd2gRjzPLG5E36PuAb2/hBmodW9BegLarRy0QCjiCc5z0OIcipZe2lN14xjeg8+eDsAPMCCeYEJ8pNNFN1Wv6T9MxCA0aq+X6pJzW1VRrPjskmf8rE2KTvKbHAFy+bbBJNhWz2pybu1MB3tyuASMUyax41wTjocC80XL9GNMCu/sf3oUR2kgk4OpcN1rHw6bNzZoT4qL0riOsA8Go9wP3Q+tEeTxNo9ddn5GQcf2nN/3VdwMrydvJ6MxbAvUpseu/xpTYjL4FhrryevB9b1rlmMqIKIa8iStNsn33UD7PwjhN3XZs0afyKkjsEDhoYCRPUr6MQHP/uQuud98P0nSaw+wgNev8MFKjxzqO8j3iVy5NwDEYlq7e22wt8TJEkMQ4RBb1dzCNsPXvOZj8htGjJFJnQbA4n/SE3ZiO7NtEEFifsenCBN8pQy9MPmXeNrvS2hFgqcZPhngh2thz4pcX9CMQndEe6MfaDAtZDqIfDmKRwYCUpvsMF5SCxPYosY46BYqc/BaFoRLjrAZnUQGvHAXk/D/f5nTaXyaO6Y2dw7EWZyH6NtDQHKQVD4Bpnn2ElQVr0Ro1hXe70CzCcbMGv7BNFDaachtQAJvrLT1Wc6ojIEccLUeJIE4Oq6RuAfeVIRB2c7olXn5KqV82oxikpi98y6GHGaXn/b7ERCqWo="
    password:
      secure: "oiki418snoHYZtr34pcVNzDKVKu+R69m3dH9jdCa7J4f0gGRe4+Ser0n2fksegOJ5UJgLn/SlpAIYQMW23fRw5yaP+VEsJpGwBDyM8quQvf89/hG/tm8QwkCaFf5StMA6io7w18k90R1rxmu0RZXH/G5t3TbeuMrBRmA3wBSsX9OYS68SA+VhEKkv43luB2j9oLBdL3OYwqlh/Jml+zcBnUoZGKHE6CeaXDHVo88kti8zAB7O+XFgwOMG9tk/KwQ2Gf9Xpt8WNzUGEtdHGY0SC4LJJMPXWClR2NaAfNb8+tASrDF6cEkRA/ceu6En8DQ7SMR2uhTb7MiaRGI0XhEs6Fyg/+gdu3hqXv5yshujInFkN4vBcGvkDVSPVKnCG1xct9mRgbhwFptgOIy9B99hnt+nTwT7SSfOXCnuD8Jdxk547wDQbKhMj3NivVYjAx5L7Ov9jtU+LVLAN+AW3qZsp5pM6IbXpTnXpCQO1nDHmlTZ5zqWpC9KYWcb+atze2nw5XlRT4gpOJh3fWfAajc9+cNaHha49EAEJgHCZXHmH7r7CV04/W9gYyrnBbUNi8EP41v3O+p1rD7dbhBYqXkaFv/NH3Nv6Qt1YEcCNEB/kgBL7zo17ETu0PsNW9hr9Iosl7Kj0kmXEqrIqj2OF9XCGfiboVT9qbheF++rT9MFKE="
    distributions: "sdist bdist_wheel"
    server: https://testpypi.python.org/pypi
    on:
      tags: true
