language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - flake8 --ignore=F401 cloud_scanner_azure
before_deploy:
  # Generate Sphinx docs
  - make sphinx
  # Generate PIP package distros
  - pip install --upgrade setuptools wheel
  - python setup.py sdist bdist_wheel
deploy:
  # Deploy Sphinx docs to github pages
  - provider: pages
    skip_cleanup: true
    local-dir: docs/build/html
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      tags: true
  # Deploy pypi package
  - provider: pypi
    skip_cleanup: true
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    server: https://test.pypi.org/legacy/
    on:
      tags: true
